name: "Scratch Org Pool Cleaner - Auto Scheduled"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

jobs:
  clean-pool:
    strategy:
      matrix:
        pool-tag: [ci, dev]
    uses: b64hub/dx-actions/.github/workflows/clean-pool.yml@main
    with:
      pool-tag: ${{ matrix.pool-tag }}
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
    env:
      SFPOWERSCRIPTS_DATADOG: "true"
      SFPOWERSCRIPTS_DATADOG_HOST: "${{ secrets.DATADOG_APP_KEY }}"
      SFPOWERSCRIPTS_DATADOG_API_KEY: "${{ secrets.DATADOG_API_KEY }}"
