# # DX@Scale CI/CD Template for GitHub
name: "Publish Metrics for Scratch Org Pools"
on:
  workflow_dispatch:
  schedule:
    # Every 30 minutes
    - cron: "30 * * * *"

env:
  SFPOWERSCRIPTS_DATADOG: "true"
  SFPOWERSCRIPTS_DATADOG_HOST: "${{ vars.DATADOG_HOST }}"
  SFPOWERSCRIPTS_DATADOG_API_KEY: "${{ secrets.DATADOG_API_KEY }}"

jobs:
  publish:
    name: "Publish Metrics"
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts
    steps:
      - name: "Authenticate Dev Hub"
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub

      - name: "Publish metrics"
        run: sfdx sfpowerscripts:pool:metrics:publish -v devhub
