name: "Replenish CI Pools - Auto Triggered"

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: "Commit Id from where the pools should be created"
        required: false
        default: "main"
  schedule:
    - cron: "0 14 * * *"

jobs:
  ci-pool:
    uses: b64hub/dx-actions/.github/workflows/prepare-pool.yml@main
    with:
      pool-tag: ci
      git-ref: ${{ inputs.git-ref }}
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}

  dev-pool:
    uses: b64hub/dx-actions/.github/workflows/prepare-pool.yml@main
    with:
      pool-tag: dev
      git-ref: ${{ inputs.git-ref }}
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
