name: "CI Pipeline - Auto Triggered"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  quickbuild:
    uses: b64hub/dx-actions/.github/workflows/quickbuild.yml@main
    with:
      datadog: true
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
      DATADOG_APP_KEY: "${{ secrets.DATADOG_APP_KEY }}"
      DATADOG_API_KEY: "${{ secrets.DATADOG_API_KEY }}"

  deploy-dev:
    uses: b64hub/dx-actions/.github/workflows/deploy.yml@main
    with:
      environment: dev
      datadog: true
    secrets:
      ENV_SFDX_AUTH_URL: ${{ secrets.DEV_SFDX_AUTH_URL }}
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
      DATADOG_APP_KEY: "${{ secrets.DATADOG_APP_KEY }}"
      DATADOG_API_KEY: "${{ secrets.DATADOG_API_KEY }}"

  build-publish:
    uses: b64hub/dx-actions/.github/workflows/build-publish.yml@main
    with:
      datadog: true
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
      DATADOG_APP_KEY: "${{ secrets.DATADOG_APP_KEY }}"
      DATADOG_API_KEY: "${{ secrets.DATADOG_API_KEY }}"
