name: "CI Pipeline - Auto Triggered"

on:
  push:
    branches:
      - main

  workflow_dispatch:

#Set the environment variables for tracking metrics
#env:
#SFPOWERSCRIPTS_NEWRELIC: 'true'
#SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INSIGHT_INSERT_KEYS }}'
#SFPOWERSCRIPTS_DATADOG: 'true'
#SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
#SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'

jobs:
  quickbuild:
    with: b64hub/dx-actions/.github/workflows/quickbuild.yml@main
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}

  deploy-dev:
    with: b64hub/dx-actions/.github/workflows/deploy.yml@main
    uses:
      org-alias: dev
    secrets:
      ENV_SFDX_AUTH_URL: ${{ secrets.DEV_SFDX_AUTH_URL }}
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}

  build-publish:
    with: b64hub/dx-actions/.github/workflows/build-publish.yml@main
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
