name: "CD Pipeline - User Triggered"

on:
  workflow_dispatch:
    inputs:
      release-def-path:
        description: "Path to release definition file"
        required: true

#Set the environment variables for tracking metrics
#env:
#SFPOWERSCRIPTS_NEWRELIC: 'true'
#SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INSIGHT_INSERT_KEYS }}'
#SFPOWERSCRIPTS_DATADOG: 'true'
#SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
#SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'

jobs:
  sit-release:
    uses: b64hub/dx-actions/.github/workflows/release.yml@main
    if: github.ref == 'refs/heads/main' || contains(github.ref,'refs/heads/release')
    with:
      release-def-path: ${{ github.event.inputs.release-def-path }}
    secrets:
      ENV_SFDX_AUTH_URL: ${{ secrets.SIT_SFDX_AUTH_URL }}

  uat-release:
    uses: b64hub/dx-actions/.github/workflows/release.yml@main
    if: contains(github.ref,'refs/heads/release')
    with:
      release-def-path: ${{ github.event.inputs.release-def-path }}
    secrets:
      ENV_SFDX_AUTH_URL: ${{ secrets.UAT_SFDX_AUTH_URL }}

  prod-release:
    uses: b64hub/dx-actions/.github/workflows/release.yml@main
    if: contains(github.ref,'refs/heads/release')
    with:
      release-def-path: ${{ github.event.inputs.release-def-path }}
    secrets:
      ENV_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
