name: "CI Pipeline - Release Build - Auto Triggered"

on:
  push:
    branches:
      - release/**
  workflow_dispatch:

jobs:
  build-publish:
    with: b64hub/dx-actions/.github/workflows/build-publish.yml@main
    secrets:
      DEVHUB_SFDX_AUTH_URL: ${{ secrets.DEVHUB_SFDX_AUTH_URL }}
    env:
      SFPOWERSCRIPTS_DATADOG: "true"
      SFPOWERSCRIPTS_DATADOG_HOST: "${{ secrets.DATADOG_APP_KEY }}"
      SFPOWERSCRIPTS_DATADOG_API_KEY: "${{ secrets.DATADOG_API_KEY }}"
